baseURL = "https://www.niskayunaco-opnurseryschool.com/"
languageCode = "en-us"
theme = "meghna-hugo"
title = "Niskayuna Co-op Nursery School"
[[menu.nav]]
URL = "#our-board"
external = false
name = "Board"
weight = 7
[[menu.nav]]
URL = "#faq"
external = false
name = "FAQ"
weight = 4
[[menu.nav]]
URL = "#teacher"
external = false
name = "Teacher"
weight = 2
[[menu.nav]]
URL = "#school"
external = false
name = "School"
weight = 3
[[menu.nav]]
URL = "#our-traditions"
external = false
name = "Traditions"
weight = 5
[[menu.nav]]
URL = "#blog"
external = false
name = "Blog"
weight = 6
[[menu.nav]]
URL = "#contact-us"
external = false
name = "Contact"
weight = 8
[[menu.nav]]
URL = "https://niskayunanurseryschool-my.sharepoint.com/:f:/g/personal/admin_niskayunaco-opnurseryschool_com/Elx4wjudw3hFkskgmojkouoBQSXwJDWvhspZlFT8TXk0Hg?e=VIhShf"
external = true
name = "Forms"
weight = 9
[[menu.nav]]
URL = "https://www.facebook.com/NiskayunaCoopNurserySchool/"
external = true
name = "Facebook"
weight = 10
[params]
custom_css = ["css/custom.css"]
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBI14J_PNWVd-m0gnUBkjmhoQyNyd7nllA"
home = "Home"
logo = "images/logo.jpg"
[params.banner]
bgImage = "images/slider/hero-area.jpg"
btn = true
btnText = "Classes"
btnURL = "#classes"
content = "Children are encouraged to be independent and self-motivated by learning through self-directed play and guided group activities. They are allowed to grow at their own pace while learning social, emotional, and intellectual skills."
enable = true
fbText = "Facebook"
fbURL = "https://www.facebook.com/NiskayunaCoopNurserySchool/"
heading = "Niskayuna Co-Op Nursery School"
icon = "tf-ion-play"
showLatestBlogPost = false
[params.counter]
bgImage = "images/backgrounds/bg-1.jpg"
enable = false
[[params.counter.counterItem]]
count = 320
icon = "tf-ion-android-happy"
title = "Happy Clients"
[[params.counter.counterItem]]
count = 565
icon = "tf-ion-archive"
title = "Projects completed"
[[params.counter.counterItem]]
count = 95
icon = "tf-ion-thumbsup"
title = "Positive feedback"
[[params.counter.counterItem]]
count = 2500
icon = "tf-ion-coffee"
title = "Cups of Coffee"
[params.cta]
btnText = "Start a project with us"
btnURL = "#"
content = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis tenetur odio impedit incidunt? Omnis accusantium ea reiciendis, fugit commodi nostrum."
enable = false
title = "Great Design & Incredible Features"
[params.footer]
copyright = "Themefisher Team"
copyrightURL = "http://www.themefisher.com"
[[params.footer.socialIcon]]
icon = "tf-ion-social-facebook"
url = "#"
[[params.footer.socialIcon]]
icon = "tf-ion-social-twitter"
url = "#"
[[params.footer.socialIcon]]
icon = "tf-ion-social-google-outline"
url = "#"
[[params.footer.socialIcon]]
icon = "tf-ion-social-youtube"
url = "#"
[[params.footer.socialIcon]]
icon = "tf-ion-social-linkedin"
url = "#"
[[params.footer.socialIcon]]
icon = "tf-ion-social-dribbble-outline"
url = "#"
[[params.footer.socialIcon]]
icon = "tf-ion-social-pinterest-outline"
url = "#"
